maps_manager_node:
  ros__parameters:
    use_sim_time: false
    map_types: [PointCloudData]
    PointCloudData:
      plugin: easynav_pointcloud_maps_manager/PointCloudMapsManager
      map_topic_in: /map_builder/cloud_filtered 
      package_name: easynav_outdoor_testcase
      map_path_file: maps/pointcloud_map.pcd
      